-- =========================================================================
-- PulseTrade Pro - Production Supabase PostgreSQL Schema (Vercel Ready)
-- Complete Cloud Database: Auth, Users, Real-Time Presence, VIP Keys, Signals & NOWPayments
-- =========================================================================

-- 1. Enable Required Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. USERS PROFILE TABLE (Source of Truth for Credits, Role, and VIP)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(20) DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN', 'VIP')),
    credits INTEGER DEFAULT 10 CHECK (credits >= 0),
    is_vip BOOLEAN DEFAULT FALSE,
    vip_expires_at TIMESTAMPTZ DEFAULT NULL,
    registration_ip VARCHAR(64) DEFAULT 'vercel_web',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_username ON public.users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_auth_id ON public.users(auth_user_id);

-- 3. AUTOMATIC AUTH TRIGGER (Creates/Updates public.users row on auth.users signup)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
DECLARE
    v_username VARCHAR(50);
    v_role VARCHAR(20);
    v_is_vip BOOLEAN;
    v_vip_exp TIMESTAMPTZ;
    v_credits INTEGER;
BEGIN
    v_username := COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1));
    v_role := CASE WHEN LOWER(NEW.email) = 'durodoluwa5@gmail.com' THEN 'ADMIN' ELSE COALESCE(NEW.raw_user_meta_data->>'role', 'USER') END;
    v_is_vip := COALESCE((NEW.raw_user_meta_data->>'is_vip')::BOOLEAN, FALSE);
    
    IF NEW.raw_user_meta_data->>'vip_expires_at' IS NOT NULL THEN
        v_vip_exp := (NEW.raw_user_meta_data->>'vip_expires_at')::TIMESTAMPTZ;
    ELSE
        v_vip_exp := NULL;
    END IF;

    IF v_is_vip OR v_role = 'ADMIN' THEN
        v_credits := 9999;
    ELSE
        v_credits := COALESCE((NEW.raw_user_meta_data->>'credits')::INTEGER, 10);
    END IF;

    INSERT INTO public.users (
        auth_user_id,
        username,
        email,
        role,
        credits,
        is_vip,
        vip_expires_at,
        registration_ip
    )
    VALUES (
        NEW.id,
        v_username,
        NEW.email,
        v_role,
        v_credits,
        v_is_vip,
        v_vip_exp,
        'supabase_auth'
    )
    ON CONFLICT (email) DO UPDATE SET
        auth_user_id = EXCLUDED.auth_user_id,
        username = EXCLUDED.username,
        role = EXCLUDED.role,
        updated_at = NOW();

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 4. REAL-TIME ACTIVE TRADER PRESENCE (Heartbeat Engine)
CREATE TABLE IF NOT EXISTS public.active_sessions (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    session_id VARCHAR(128) NOT NULL UNIQUE,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    ip_address VARCHAR(64) DEFAULT 'client_connection',
    active_asset VARCHAR(32) DEFAULT 'EUR/USD',
    last_heartbeat TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_active_sessions_heartbeat ON public.active_sessions(last_heartbeat);

-- 5. PROTECTED 30-DAY VIP ALLOCATION KEYS
CREATE TABLE IF NOT EXISTS public.vip_keys (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    vip_code VARCHAR(64) NOT NULL UNIQUE,
    duration_days INTEGER DEFAULT 30,
    max_uses INTEGER DEFAULT 9999,
    used_count INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.vip_keys (vip_code, duration_days, max_uses, is_active)
VALUES 
    ('VIP-ALPHA-30D', 30, 9999, TRUE),
    ('PULSE-VIP-2026', 30, 9999, TRUE),
    ('QUANT-30D', 30, 9999, TRUE),
    ('VIP-TRADER-1M', 30, 9999, TRUE)
ON CONFLICT (vip_code) DO NOTHING;

-- 6. QUANTITATIVE SIGNALS TABLE
CREATE TABLE IF NOT EXISTS public.signals (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    asset VARCHAR(32) NOT NULL,
    timeframe VARCHAR(16) NOT NULL,
    direction VARCHAR(8) NOT NULL CHECK (direction IN ('CALL', 'PUT', 'BUY', 'SELL')),
    entry_price NUMERIC(16, 5) NOT NULL,
    target_price NUMERIC(16, 5),
    stop_loss NUMERIC(16, 5),
    take_profit_1 NUMERIC(16, 5),
    take_profit_2 NUMERIC(16, 5),
    confidence NUMERIC(5, 2) NOT NULL,
    confluence_factors JSONB DEFAULT '[]'::JSONB,
    setup_name VARCHAR(128),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_signals_created_at ON public.signals(created_at DESC);

-- 7. VERIFIED TRADE OUTCOMES & ACCURACY AUDIT
CREATE TABLE IF NOT EXISTS public.trade_outcomes (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    signal_id UUID REFERENCES public.signals(id) ON DELETE SET NULL,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    asset VARCHAR(32) NOT NULL,
    timeframe VARCHAR(16) NOT NULL,
    direction VARCHAR(8) NOT NULL,
    entry_price NUMERIC(16, 5),
    outcome VARCHAR(8) NOT NULL CHECK (outcome IN ('WIN', 'LOSS', 'DRAW')),
    logged_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. APP SETTINGS (Branding & NOWPayments Configuration)
CREATE TABLE IF NOT EXISTS public.app_settings (
    key VARCHAR(64) PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.app_settings (key, value)
VALUES 
  ('site_branding', '{
    "siteName": "PulseTrade Pro",
    "siteTagline": "Institutional-Grade Quantitative Micro-Volatility Terminal",
    "logoUrl": "",
    "logoIcon": "zap",
    "badgeText": "v8.2 QUANT",
    "bannerText": "⚡ 30-Day VIP Pass: Institutional-grade 89.4% confluence signals with instant automated verification",
    "bannerEnabled": true,
    "supportTelegram": "https://t.me/pulsetrade_quant",
    "supportWhatsapp": "",
    "supportEmail": "support@pulsetrade.pro",
    "vipPriceUsd": 49.0,
    "starterPriceUsd": 5.0,
    "themeAccent": "emerald"
  }'::JSONB),
  ('nowpayments_config', '{
    "apiKey": "",
    "ipnSecret": "",
    "isSandbox": false,
    "enabled": false,
    "payoutAddress": ""
  }'::JSONB)
ON CONFLICT (key) DO NOTHING;

-- 9. PAYMENT ORDERS TABLE (For NOWPayments Crypto Invoices)
CREATE TABLE IF NOT EXISTS public.payment_orders (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    payment_id VARCHAR(128) NOT NULL UNIQUE,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    order_id VARCHAR(128) NOT NULL,
    product_type VARCHAR(32) DEFAULT 'VIP_30D',
    price_amount NUMERIC(16, 2) NOT NULL,
    price_currency VARCHAR(16) DEFAULT 'USD',
    pay_address TEXT,
    pay_amount NUMERIC(16, 8),
    pay_currency VARCHAR(16),
    status VARCHAR(32) DEFAULT 'waiting',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payment_orders_payment_id ON public.payment_orders(payment_id);

-- 10. ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.active_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trade_outcomes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_orders ENABLE ROW LEVEL SECURITY;

-- Clean existing policies safely
DROP POLICY IF EXISTS "Public Read Users" ON public.users;
DROP POLICY IF EXISTS "Public Upsert Users" ON public.users;
DROP POLICY IF EXISTS "Public Update Users" ON public.users;
DROP POLICY IF EXISTS "Public Read Active Sessions" ON public.active_sessions;
DROP POLICY IF EXISTS "Public Upsert Active Sessions" ON public.active_sessions;
DROP POLICY IF EXISTS "Public Read VIP Keys" ON public.vip_keys;
DROP POLICY IF EXISTS "Public Update VIP Keys" ON public.vip_keys;
DROP POLICY IF EXISTS "Public Read Signals" ON public.signals;
DROP POLICY IF EXISTS "Public Insert Signals" ON public.signals;
DROP POLICY IF EXISTS "Public Read Outcomes" ON public.trade_outcomes;
DROP POLICY IF EXISTS "Public Insert Outcomes" ON public.trade_outcomes;
DROP POLICY IF EXISTS "Public Read Settings" ON public.app_settings;
DROP POLICY IF EXISTS "Public Upsert Settings" ON public.app_settings;
DROP POLICY IF EXISTS "Public Read Orders" ON public.payment_orders;
DROP POLICY IF EXISTS "Public Upsert Orders" ON public.payment_orders;

-- Users policies: allow read, insert, update
CREATE POLICY "Public Read Users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Public Upsert Users" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Users" ON public.users FOR UPDATE USING (true) WITH CHECK (true);

-- Active sessions: public select & upsert for presence counter
CREATE POLICY "Public Read Active Sessions" ON public.active_sessions FOR SELECT USING (true);
CREATE POLICY "Public Upsert Active Sessions" ON public.active_sessions FOR ALL USING (true) WITH CHECK (true);

-- VIP keys: public read active keys and increment used_count
CREATE POLICY "Public Read VIP Keys" ON public.vip_keys FOR SELECT USING (is_active = TRUE);
CREATE POLICY "Public Update VIP Keys" ON public.vip_keys FOR UPDATE USING (true) WITH CHECK (true);

-- Signals: public read & insert
CREATE POLICY "Public Read Signals" ON public.signals FOR SELECT USING (true);
CREATE POLICY "Public Insert Signals" ON public.signals FOR INSERT WITH CHECK (true);

-- Trade outcomes: public read & insert
CREATE POLICY "Public Read Outcomes" ON public.trade_outcomes FOR SELECT USING (true);
CREATE POLICY "Public Insert Outcomes" ON public.trade_outcomes FOR INSERT WITH CHECK (true);

-- App Settings: public read and admin upsert
CREATE POLICY "Public Read Settings" ON public.app_settings FOR SELECT USING (true);
CREATE POLICY "Public Upsert Settings" ON public.app_settings FOR ALL USING (true) WITH CHECK (true);

-- Payment orders: public read and upsert
CREATE POLICY "Public Read Orders" ON public.payment_orders FOR SELECT USING (true);
CREATE POLICY "Public Upsert Orders" ON public.payment_orders FOR ALL USING (true) WITH CHECK (true);

-- 11. ENABLE REALTIME BROADCASTING
DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.active_sessions;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.signals;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.trade_outcomes;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.app_settings;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_object THEN NULL;
END $$;

-- 12. DEFAULT ADMIN RECORD (Instant Access)
INSERT INTO public.users (username, email, role, credits, is_vip, vip_expires_at, registration_ip)
VALUES ('admin', 'durodoluwa5@gmail.com', 'ADMIN', 9999, TRUE, NOW() + INTERVAL '365 days', '127.0.0.1')
ON CONFLICT (email) DO UPDATE SET
    role = 'ADMIN',
    credits = 9999,
    is_vip = TRUE,
    vip_expires_at = NOW() + INTERVAL '365 days';
