import React, { useState, useEffect } from 'react';
import {
  getSupabaseConfig,
  isSupabaseConfigured,
  saveCustomSupabaseConfig,
  testSupabaseConnection,
} from '../utils/supabaseClient.ts';

interface SupabaseManagerProps {
  onlineUsers?: number;
  onLaunchCockpit?: () => void;
}

export function SupabaseManager({ onlineUsers = 1, onLaunchCockpit }: SupabaseManagerProps) {
  const [config, setConfig] = useState(getSupabaseConfig());
  const [testResult, setTestResult] = useState<{
    tested: boolean;
    success?: boolean;
    message?: string;
    loading?: boolean;
  }>({ tested: false });
  const [copiedSql, setCopiedSql] = useState(false);
  const [copiedEnv, setCopiedEnv] = useState(false);
  const [activeTab, setActiveTab] = useState<'connect' | 'sql' | 'checklist'>('connect');

  const isConfigured = isSupabaseConfigured();

  // Test current configuration on mount if URL is present
  useEffect(() => {
    if (config.url && config.anonKey) {
      handleTestConnection();
    }
  }, []);

  const handleTestConnection = async () => {
    if (!config.url || !config.anonKey) {
      setTestResult({
        tested: true,
        success: false,
        message: 'Please provide both Supabase Project URL and Anon Public Key.',
      });
      return;
    }

    setTestResult({ tested: true, loading: true });
    const result = await testSupabaseConnection(config.url, config.anonKey);
    setTestResult({
      tested: true,
      loading: false,
      success: result.success,
      message: result.message,
    });

    if (result.success) {
      saveCustomSupabaseConfig(config.url, config.anonKey);
    }
  };

  const handleSaveCredentials = () => {
    saveCustomSupabaseConfig(config.url, config.anonKey);
    handleTestConnection();
  };

  const handleCopySql = () => {
    // Fetch schema content or copy embedded SQL
    const sqlContent = `-- PulseTrade Pro - Production Supabase PostgreSQL Schema
-- Copy and paste this into Supabase SQL Editor:
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    role VARCHAR(20) DEFAULT 'USER',
    credits INTEGER DEFAULT 10,
    is_vip BOOLEAN DEFAULT FALSE,
    vip_expires_at TIMESTAMPTZ DEFAULT NULL,
    registration_ip VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 100% Genuine Active Real-Time Presence
CREATE TABLE IF NOT EXISTS public.active_sessions (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    session_id VARCHAR(128) NOT NULL UNIQUE,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    ip_address VARCHAR(64) NOT NULL,
    active_asset VARCHAR(32) DEFAULT 'EUR/USD',
    last_heartbeat TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_active_sessions_heartbeat ON public.active_sessions(last_heartbeat);

CREATE TABLE IF NOT EXISTS public.signals (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    asset VARCHAR(32) NOT NULL,
    timeframe VARCHAR(16) NOT NULL,
    direction VARCHAR(8) NOT NULL,
    entry_price NUMERIC(16, 5) NOT NULL,
    target_price NUMERIC(16, 5),
    stop_loss NUMERIC(16, 5),
    take_profit_1 NUMERIC(16, 5),
    take_profit_2 NUMERIC(16, 5),
    confidence NUMERIC(5, 2) NOT NULL,
    confluence_factors JSONB DEFAULT '[]'::JSONB,
    setup_name VARCHAR(128),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.trade_outcomes (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    signal_id UUID REFERENCES public.signals(id) ON DELETE SET NULL,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    asset VARCHAR(32) NOT NULL,
    timeframe VARCHAR(16) NOT NULL,
    direction VARCHAR(8) NOT NULL,
    entry_price NUMERIC(16, 5),
    outcome VARCHAR(8) NOT NULL CHECK (outcome IN ('WIN', 'LOSS', 'DRAW')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.vip_keys (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    vip_code VARCHAR(64) NOT NULL UNIQUE,
    duration_days INTEGER DEFAULT 30,
    max_uses INTEGER DEFAULT 100,
    used_count INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Site Branding & Platform Settings (Real-time Configurable)
CREATE TABLE IF NOT EXISTS public.app_settings (
    key VARCHAR(64) PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.vip_keys (vip_code, duration_days, max_uses, is_active)
VALUES ('VIP-ALPHA-30D', 30, 100, TRUE), ('PULSE-VIP-2026', 30, 100, TRUE), ('FOREX-PRO-MT5', 30, 100, TRUE)
ON CONFLICT (vip_code) DO NOTHING;

-- Seed Default Branding
INSERT INTO public.app_settings (key, value)
VALUES 
  ('site_branding', '{"siteName":"PulseTrade Pro","siteTagline":"Institutional-Grade Quantitative Micro-Volatility Terminal","logoUrl":"","logoIcon":"zap","badgeText":"v8.2 QUANT","bannerText":"⚡ 30-Day VIP Pass: Institutional-grade 89.4% confluence signals with instant automated verification","bannerEnabled":true,"supportTelegram":"https://t.me/pulsetrade_quant","supportWhatsapp":"","supportEmail":"support@pulsetrade.pro","vipPriceUsd":49,"starterPriceUsd":5,"themeAccent":"emerald"}'::jsonb),
  ('nowpayments_config', '{"apiKey":"","ipnSecret":"","isSandbox":false,"enabled":false}'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- Enable Realtime Publication
DO $$ BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.active_sessions;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.signals;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.trade_outcomes;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.app_settings;
EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- Row Level Security (RLS)
ALTER TABLE public.active_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trade_outcomes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Active Sessions" ON public.active_sessions FOR SELECT USING (true);
CREATE POLICY "Public Upsert Active Sessions" ON public.active_sessions FOR ALL USING (true);
CREATE POLICY "Public Read Signals" ON public.signals FOR SELECT USING (true);
CREATE POLICY "Public Read Outcomes" ON public.trade_outcomes FOR SELECT USING (true);
CREATE POLICY "Public Read Users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Public Read App Settings" ON public.app_settings FOR SELECT USING (true);
CREATE POLICY "Public Upsert App Settings" ON public.app_settings FOR ALL USING (true);
`;

    navigator.clipboard.writeText(sqlContent);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 3000);
  };

  const handleCopyEnv = () => {
    const envText = `VITE_SUPABASE_URL="${config.url || 'https://your-project.supabase.co'}"\nVITE_SUPABASE_ANON_KEY="${config.anonKey || 'your-anon-public-key'}"\nSUPABASE_SERVICE_ROLE_KEY="your-service-role-secret-key"`;
    navigator.clipboard.writeText(envText);
    setCopiedEnv(true);
    setTimeout(() => setCopiedEnv(false), 3000);
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto py-2">
      {/* Header Banner */}
      <div className="bg-gradient-to-br from-slate-900 via-slate-900 to-emerald-950/40 border border-slate-800 rounded-3xl p-6 shadow-2xl relative overflow-hidden">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse" />
              <span className="text-xs font-mono font-bold text-emerald-400 uppercase tracking-widest">
                Cloud Architecture &amp; Database
              </span>
            </div>
            <h2 className="text-2xl font-black text-white font-mono tracking-tight">
              Supabase PostgreSQL &amp; Real-Time Integration
            </h2>
            <p className="text-xs text-slate-400 max-w-xl">
              Connect your live Supabase online database to store user accounts, 30-day VIP activations, 100% genuine real-time active trader presence, and algorithmic trade history.
            </p>
          </div>

          <div className="flex items-center gap-3 bg-slate-950/80 border border-slate-800 px-4 py-2.5 rounded-2xl">
            <div className="text-right">
              <div className="text-[10px] font-mono text-slate-400 uppercase">Live Real-Time Active</div>
              <div className="text-lg font-black font-mono text-emerald-400">
                {onlineUsers} {onlineUsers === 1 ? 'Trader' : 'Traders'} Online
              </div>
            </div>
            <div className="w-3 h-3 rounded-full bg-emerald-400 animate-ping" />
          </div>
        </div>

        {/* Navigation Tabs */}
        <div className="flex items-center gap-2 mt-6 border-b border-slate-800/80 pb-2">
          <button
            type="button"
            onClick={() => setActiveTab('connect')}
            className={`px-4 py-2 rounded-xl text-xs font-mono font-bold transition ${
              activeTab === 'connect'
                ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            1. Connect Credentials
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('sql')}
            className={`px-4 py-2 rounded-xl text-xs font-mono font-bold transition ${
              activeTab === 'sql'
                ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            2. Copy SQL Schema
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('checklist')}
            className={`px-4 py-2 rounded-xl text-xs font-mono font-bold transition ${
              activeTab === 'checklist'
                ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            3. Deployment Readiness
          </button>
        </div>
      </div>

      {/* TAB 1: CONNECT SUPABASE */}
      {activeTab === 'connect' && (
        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-6">
          <div className="space-y-1">
            <h3 className="text-base font-bold font-mono text-white">Supabase Project API Keys</h3>
            <p className="text-xs text-slate-400">
              Get these from your{' '}
              <a
                href="https://supabase.com/dashboard"
                target="_blank"
                rel="noreferrer"
                className="text-emerald-400 underline hover:text-emerald-300"
              >
                Supabase Dashboard &rarr; Project Settings &rarr; API
              </a>
              . You can paste them here to connect instantly!
            </p>
          </div>

          <div className="space-y-4">
            <div>
              <label className="block text-xs font-mono text-slate-300 mb-1.5 font-bold">
                Project URL (VITE_SUPABASE_URL)
              </label>
              <input
                type="text"
                value={config.url}
                onChange={(e) => setConfig({ ...config, url: e.target.value.trim() })}
                placeholder="https://xyzabcdefghijklm.supabase.co"
                className="w-full bg-slate-950 border border-slate-700/80 rounded-xl px-4 py-3 text-xs font-mono text-white placeholder-slate-600 focus:outline-none focus:border-emerald-400"
              />
            </div>

            <div>
              <label className="block text-xs font-mono text-slate-300 mb-1.5 font-bold">
                Anon Public API Key (VITE_SUPABASE_ANON_KEY)
              </label>
              <textarea
                rows={2}
                value={config.anonKey}
                onChange={(e) => setConfig({ ...config, anonKey: e.target.value.trim() })}
                placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                className="w-full bg-slate-950 border border-slate-700/80 rounded-xl px-4 py-3 text-xs font-mono text-white placeholder-slate-600 focus:outline-none focus:border-emerald-400"
              />
            </div>

            {/* Test Status Banner */}
            {testResult.tested && (
              <div
                className={`p-4 rounded-2xl border text-xs font-mono flex items-center justify-between gap-3 ${
                  testResult.loading
                    ? 'bg-amber-500/10 border-amber-500/30 text-amber-300'
                    : testResult.success
                    ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-300'
                    : 'bg-rose-500/10 border-rose-500/30 text-rose-300'
                }`}
              >
                <div className="flex items-center gap-2.5">
                  {testResult.loading ? (
                    <span className="w-4 h-4 border-2 border-amber-400 border-t-transparent rounded-full animate-spin" />
                  ) : testResult.success ? (
                    <svg className="w-5 h-5 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M5 13l4 4L19 7" />
                    </svg>
                  ) : (
                    <svg className="w-5 h-5 text-rose-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  )}
                  <span>{testResult.message}</span>
                </div>
              </div>
            )}

            <div className="flex flex-wrap items-center gap-3 pt-2">
              <button
                type="button"
                onClick={handleSaveCredentials}
                disabled={testResult.loading}
                className="px-5 py-3 bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-mono font-bold text-xs rounded-xl shadow-lg shadow-emerald-500/20 transition active:scale-95 flex items-center gap-2"
              >
                {testResult.loading ? 'Testing Connection...' : 'Connect & Test Supabase'}
              </button>
              <button
                type="button"
                onClick={handleCopyEnv}
                className="px-4 py-3 bg-slate-800 hover:bg-slate-700 text-slate-200 font-mono font-bold text-xs rounded-xl transition flex items-center gap-2"
              >
                {copiedEnv ? '✓ Copied .env Variables!' : 'Copy .env Configuration'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: COPY SQL SCHEMA */}
      {activeTab === 'sql' && (
        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-5">
          <div className="flex items-center justify-between flex-wrap gap-3">
            <div>
              <h3 className="text-base font-bold font-mono text-white">Supabase SQL Schema (supabase_schema.sql)</h3>
              <p className="text-xs text-slate-400">
                1. Click the button below to copy the SQL script.
                <br />
                2. Open your Supabase Dashboard &rarr; <strong>SQL Editor</strong> &rarr; Click <strong>New Query</strong>.
                <br />
                3. Paste and click <strong>Run</strong>.
              </p>
            </div>

            <button
              type="button"
              onClick={handleCopySql}
              className="px-5 py-2.5 bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-mono font-bold text-xs rounded-xl shadow-lg shadow-emerald-500/20 transition active:scale-95 flex items-center gap-2"
            >
              {copiedSql ? (
                <>
                  <svg className="w-4 h-4 text-slate-950" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M5 13l4 4L19 7" />
                  </svg>
                  <span>✓ COPIED TO CLIPBOARD!</span>
                </>
              ) : (
                <>
                  <svg className="w-4 h-4 text-slate-950" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                    />
                  </svg>
                  <span>COPY SQL SCRIPT</span>
                </>
              )}
            </button>
          </div>

          <div className="bg-slate-950 border border-slate-800 rounded-2xl p-4 font-mono text-[11px] text-slate-300 max-h-96 overflow-y-auto space-y-2">
            <div className="text-emerald-400 font-bold">-- Ready to paste into Supabase SQL Editor:</div>
            <pre className="text-slate-400 whitespace-pre-wrap leading-relaxed">
{`-- 1. USERS & PROFILES TABLE
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    role VARCHAR(20) DEFAULT 'USER',
    credits INTEGER DEFAULT 10,
    is_vip BOOLEAN DEFAULT FALSE,
    vip_expires_at TIMESTAMPTZ DEFAULT NULL,
    registration_ip VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 100% REAL-TIME ACTIVE TRADERS PRESENCE
CREATE TABLE IF NOT EXISTS public.active_sessions (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    session_id VARCHAR(128) NOT NULL UNIQUE,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    ip_address VARCHAR(64) NOT NULL,
    active_asset VARCHAR(32) DEFAULT 'EUR/USD',
    last_heartbeat TIMESTAMPTZ DEFAULT NOW()
);

-- 3. QUANTITATIVE SIGNALS (BINARY & MT5 FOREX)
CREATE TABLE IF NOT EXISTS public.signals (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    asset VARCHAR(32) NOT NULL,
    timeframe VARCHAR(16) NOT NULL,
    direction VARCHAR(8) NOT NULL,
    entry_price NUMERIC(16, 5) NOT NULL,
    target_price NUMERIC(16, 5),
    stop_loss NUMERIC(16, 5),
    take_profit_1 NUMERIC(16, 5),
    take_profit_2 NUMERIC(16, 5),
    confidence NUMERIC(5, 2) NOT NULL,
    confluence_factors JSONB DEFAULT '[]'::JSONB,
    setup_name VARCHAR(128),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TRADE OUTCOME AUDIT LOG
CREATE TABLE IF NOT EXISTS public.trade_outcomes (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    asset VARCHAR(32) NOT NULL,
    direction VARCHAR(8) NOT NULL,
    outcome VARCHAR(8) NOT NULL CHECK (outcome IN ('WIN', 'LOSS', 'DRAW')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. REAL-TIME PUBLICATION
ALTER PUBLICATION supabase_realtime ADD TABLE public.active_sessions;
ALTER PUBLICATION supabase_realtime ADD TABLE public.signals;`}
            </pre>
          </div>
        </div>
      )}

      {/* TAB 3: DEPLOYMENT READINESS CHECKLIST */}
      {activeTab === 'checklist' && (
        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-4">
          <h3 className="text-base font-bold font-mono text-white">Production Deployment Verification</h3>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-2">
            <div className="bg-slate-950/80 border border-emerald-500/30 rounded-2xl p-4 space-y-2">
              <div className="flex items-center gap-2 text-emerald-400 font-mono text-xs font-bold">
                <span>✓</span>
                <span>Real-Time Active Traders Counter</span>
              </div>
              <p className="text-[11px] text-slate-400">
                100% genuine presence tracking via active 35-second sliding heartbeat window. Shows exact active connected clients without artificial floor.
              </p>
            </div>

            <div className="bg-slate-950/80 border border-emerald-500/30 rounded-2xl p-4 space-y-2">
              <div className="flex items-center gap-2 text-emerald-400 font-mono text-xs font-bold">
                <span>✓</span>
                <span>MetaTrader 5 (MT5) Forex Module</span>
              </div>
              <p className="text-[11px] text-slate-400">
                Full MT5 parameters: Exact Entry, Stop Loss (SL), Take Profit (TP1 &amp; TP2), Account Lot Size calculator, and 1-click clipboard copier.
              </p>
            </div>

            <div className="bg-slate-950/80 border border-emerald-500/30 rounded-2xl p-4 space-y-2">
              <div className="flex items-center gap-2 text-emerald-400 font-mono text-xs font-bold">
                <span>✓</span>
                <span>Live Deriv WebSocket Feed</span>
              </div>
              <p className="text-[11px] text-slate-400">
                Subscribes directly to Deriv real-time tick API (wss://ws.derivws.com/websockets/v3) for 24/7 continuous mathematical calculation.
              </p>
            </div>

            <div className="bg-slate-950/80 border border-emerald-500/30 rounded-2xl p-4 space-y-2">
              <div className="flex items-center gap-2 text-emerald-400 font-mono text-xs font-bold">
                <span>✓</span>
                <span>Supabase PostgreSQL Schema</span>
              </div>
              <p className="text-[11px] text-slate-400">
                Complete schema ready in <code className="text-emerald-400">supabase_schema.sql</code> with Row Level Security, indexes, and Realtime Publications.
              </p>
            </div>

            <div className="bg-slate-950/80 border border-emerald-500/30 rounded-2xl p-4 space-y-2">
              <div className="flex items-center gap-2 text-emerald-400 font-mono text-xs font-bold">
                <span>✓</span>
                <span>Anti-Abuse &amp; 30-Day VIP Engine</span>
              </div>
              <p className="text-[11px] text-slate-400">
                Guards starter credits, prevents multiple account spam per IP, and tracks 30-day VIP expirations down to the second.
              </p>
            </div>

            <div className="bg-slate-950/80 border border-emerald-500/30 rounded-2xl p-4 space-y-2">
              <div className="flex items-center gap-2 text-emerald-400 font-mono text-xs font-bold">
                <span>✓</span>
                <span>Production Server &amp; Container Ready</span>
              </div>
              <p className="text-[11px] text-slate-400">
                Dual Node.js TypeScript and PHP router with autonomous graceful failover, ready for Cloud Run container deployment.
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
